<?php
    define('PROJECT', '/MVC_CRUD_conccesionario3/Framework_PHP_OOP_MVC/');
    define('SITE_ROOT', $_SERVER['DOCUMENT_ROOT'] . PROJECT);
    define('SITE_PATH', 'http://' . $_SERVER['HTTP_HOST'] . PROJECT);
    define('PRODUCTION', true);
    define('MODEL_PATH', SITE_ROOT . 'model/');
    define('MODULES_PATH', SITE_ROOT . 'module/');
    define('RESOURCES', SITE_ROOT . 'resources/');
    define('UTILS', SITE_ROOT . 'utils/');
    $iconos = parse_ini_file(UTILS."iconos.ini");   
    define('ICONOS',$iconos['url']);
    define('VIEW_PATH_INC', SITE_ROOT . 'view/inc/');
    define('CSS_PATH', SITE_ROOT . 'view/css/');
    define('JS_PATH', SITE_ROOT . 'view/js/');
    define('IMG_PATH', SITE_ROOT . 'view/images/');
    define('UTILS_HOME', SITE_ROOT . 'module/home/utils/');
    define('DAO_HOME', SITE_ROOT . 'module/home/model/DAO/');
    define('BLL_HOME', SITE_ROOT . 'module/home/model/BLL/');
    define('MODEL_HOME', SITE_ROOT . 'module/home/model/model/');
    define('JS_VIEW_HOME', SITE_PATH . 'module/home/view/js/');
    define ('VIEW_PATH_HOME', SITE_ROOT . 'module/home/view/');
    define('DAO_SEARCH', SITE_ROOT . 'module/search/model/DAO/');
    define('BLL_SEARCH', SITE_ROOT . 'module/search/model/BLL/');
    define('MODEL_SEARCH', SITE_ROOT . 'module/search/model/model/');
    define('JS_VIEW_SEARCH', SITE_PATH . 'module/search/view/js/');
    define('UTILS_SHOP', SITE_ROOT . 'module/shop/utils/');
    define('DAO_SHOP', SITE_ROOT . 'module/shop/model/DAO/');
    define('BLL_SHOP', SITE_ROOT . 'module/shop/model/BLL/');
    define('MODEL_SHOP', SITE_ROOT . 'module/shop/model/model/');
    define('JS_VIEW_SHOP', SITE_PATH . 'module/shop/view/js/');
    define ('VIEW_PATH_SHOP', SITE_ROOT . 'module/shop/view/');
    define('UTILS_CART', SITE_ROOT . 'module/cart/utils/');
    define('DAO_CART', SITE_ROOT . 'module/cart/model/DAO/');
    define('BLL_CART', SITE_ROOT . 'module/cart/model/BLL/');
    define('MODEL_CART', SITE_ROOT . 'module/cart/model/model/');
    define('JS_VIEW_CART', SITE_PATH . 'module/cart/view/js/');
    define ('VIEW_PATH_CART', SITE_ROOT . 'module/cart/view/');
    define('MODEL_CONTACT', SITE_ROOT . 'module/contact/model/model/');
    define('JS_VIEW_CONTACT', SITE_PATH . 'module/contact/view/js/');
    define ('VIEW_PATH_CONTACT', SITE_ROOT . 'module/contact/view/');
    define('UTILS_LOGIN', SITE_ROOT . 'module/login/utils/');
    define('DAO_LOGIN', SITE_ROOT . 'module/login/model/DAO/');
    define('BLL_LOGIN', SITE_ROOT . 'module/login/model/BLL/');
    define('MODEL_LOGIN', SITE_ROOT . 'module/login/model/model/');
    define('JS_VIEW_LOGIN', SITE_PATH . 'module/login/view/js/');
    define ('VIEW_PATH_LOGIN', SITE_ROOT . 'module/login/view/');
    define('URL_FRIENDLY', TRUE);
